import { cp, mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const apiDir = join(root, 'api');
const stagingDir = join(root, '.vercel-api-routes');
const generatedIndex = join(apiDir, 'index.ts');
const force = process.argv.includes('--force');
const check = process.argv.includes('--check');
const runningOnVercel = process.env.VERCEL === '1' || process.env.VERCEL === 'true';

const CODE_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.tsx']);

function shouldPrepare() {
  return force || runningOnVercel;
}

function isCodeFile(relativePath) {
  return CODE_EXTENSIONS.has(extname(relativePath));
}

// Files that must stay in api/ after staging. Every non-underscore code file
// under api/ becomes a Vercel function, so the single generated index.ts must
// be the only such file left behind. Underscore helpers stay because
// server/_shared modules import them through ../../api/_x.js paths (and they
// are never deployed as functions); test files stay and are removed from the
// deployment by .vercelignore.
function staysInApi(relativePath) {
  const fileName = basename(relativePath);
  if (fileName.startsWith('_')) return true;
  if (/\.(test|spec)\./.test(relativePath)) return true;
  if (!isCodeFile(relativePath)) return true;
  // api/mcp.ts must stay a real function: vercel.json rewrites /mcp and
  // /.well-known/mcp -> /api/mcp, which resolve to the function directly
  // (rewrite destinations are not re-routed through the /api/(.*) rewrite).
  // It is also a material source for the /mcp URL in build:sitemap's static
  // manifest, so removing it fails build:sitemap.
  if (relativePath === 'mcp.ts') return true;
  // The api/mcp/ implementation tree moves into .vercel-api-routes/mcp/ so
  // Vercel doesn't count every nested .ts file as a separate function (the
  // free plan is limited to 12). api/mcp.ts imports are rewritten to point
  // at the staged tree and generate-public-product-facts.mjs is patched to
  // dynamically import from .vercel-api-routes/ instead.
  return false;
}

function routePathFromFile(relativePath) {
  const extension = extname(relativePath);
  const withoutExtension = relativePath.slice(0, -extension.length);
  const parts = withoutExtension.split(sep);
  const fileName = parts.at(-1) ?? '';

  if (
    !['.js', '.ts'].includes(extension) ||
    fileName.startsWith('_') ||
    fileName.endsWith('.test') ||
    relativePath.startsWith('mcp/') ||
    relativePath === 'not-found.ts'
  ) {
    return null;
  }

  const routeParts = parts.map((part) => {
    if (part.startsWith('[...') && part.endsWith(']')) return '*';
    if (part.startsWith('[') && part.endsWith(']')) return `:${part.slice(1, -1)}`;
    return part;
  });
  return `/${routeParts.join('/')}`;
}

async function collectFiles(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relativePath = prefix ? join(prefix, entry.name) : entry.name;
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(join(directory, entry.name), relativePath)));
    } else {
      files.push(relativePath);
    }
  }
  return files;
}

function sortRoutes(routes) {
  return routes.sort((left, right) => {
    const leftDynamic = left.routePath.includes(':') || left.routePath.includes('*');
    const rightDynamic = right.routePath.includes(':') || right.routePath.includes('*');
    if (leftDynamic !== rightDynamic) return leftDynamic ? 1 : -1;
    if (left.routePath.includes('*') !== right.routePath.includes('*')) {
      return left.routePath.includes('*') ? 1 : -1;
    }
    return right.routePath.length - left.routePath.length;
  });
}

function renderIndex(routes) {
  const loaders = routes
    .map(({ routePath, relativePath }) => {
      const modulePath = relativePath.slice(0, -extname(relativePath).length).split(sep).join('/');
      return `  ${JSON.stringify(routePath)}: () => import('../.vercel-api-routes/${modulePath}'),`;
    })
    .join('\n');

  const nodeStyleRoutes = JSON.stringify(['/story', '/og-story']);

  return `// @ts-nocheck
/* AUTO-GENERATED by scripts/prepare-vercel.mjs. Do not edit. */
// Vercel sees this file as the only API function. The source route modules are
// staged in .vercel-api-routes/ (same depth as api/, so relative imports of
// ../server/... keep resolving) and loaded through this generated static
// import map.

const routeLoaders = {
${loaders}
};
const nodeStyleRoutes = new Set(${nodeStyleRoutes});
const routePatterns = Object.entries(routeLoaders).map(([pattern, load]) => ({ pattern, load }));

function requestUrl(req) {
  const host = req.headers?.host || 'localhost';
  const protocol = req.headers?.['x-forwarded-proto'] || 'https';
  const rawUrl = req.url || '/';
  const url = new URL(rawUrl, protocol + '://' + host);
  const stagedRoute = url.searchParams.get('__wm_route');

  // The rewrite carries the original route explicitly. The header fallbacks
  // cover Vercel preview invocations and direct calls to /api/index.
  if (stagedRoute !== null) {
    url.searchParams.delete('__wm_route');
    url.pathname = '/api/' + stagedRoute.replace(/^\\/+/, '');
  } else if (url.pathname === '/api/index' || url.pathname === '/api/index.ts') {
    const originalPath = req.headers?.['x-matched-path'] || req.headers?.['x-original-url'];
    if (typeof originalPath === 'string' && originalPath.startsWith('/api/')) {
      const original = new URL(originalPath, url);
      url.pathname = original.pathname;
      url.search = original.search;
    }
  }
  return url;
}

function routeMatches(pattern, pathname) {
  const patternParts = pattern.split('/').filter(Boolean);
  const pathParts = pathname.split('/').filter(Boolean);
  if (patternParts.at(-1) === '*') {
    if (pathParts.length < patternParts.length - 1) return false;
  } else if (patternParts.length !== pathParts.length) {
    return false;
  }
  return patternParts.every((part, index) => part === '*' || part.startsWith(':') || part === pathParts[index]);
}

function findRoute(pathname) {
  const apiPath = pathname.replace(/^\\/api(?=\\/$|\\/)/, '') || '/';
  return routePatterns.find(({ pattern }) => routeMatches(pattern, apiPath));
}

function webRequest(req, url) {
  const headers = new Headers();
  for (const [name, value] of Object.entries(req.headers || {})) {
    if (Array.isArray(value)) headers.set(name, value.join(', '));
    else if (value != null) headers.set(name, String(value));
  }
  const init = { method: req.method || 'GET', headers };
  if (init.method !== 'GET' && init.method !== 'HEAD') {
    init.body = req;
    init.duplex = 'half';
  }
  return new Request(url, init);
}

async function sendWebResponse(res, response) {
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  if (!response.body) {
    res.end();
    return;
  }
  const reader = response.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      res.write(value);
    }
  } finally {
    res.end();
  }
}

export default async function handler(req, res) {
  const url = requestUrl(req);
  const route = findRoute(url.pathname);
  if (!route) {
    res.statusCode = 404;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'Route not found' }));
    return;
  }

  try {
    const module = await route.load();
    const routeHandler = module.default;
    if (typeof routeHandler !== 'function') throw new Error('Route has no default handler');

    if (nodeStyleRoutes.has(route.pattern)) {
      await routeHandler(req, res);
      return;
    }

    const response = await routeHandler(
      webRequest(req, url),
      { waitUntil: (promise) => Promise.resolve(promise).catch(() => {}) },
    );
    if (response instanceof Response) {
      await sendWebResponse(res, response);
    } else if (!res.writableEnded) {
      res.statusCode = 500;
      res.end(JSON.stringify({ error: 'Route did not return a Response' }));
    }
  } catch (error) {
    console.error('[Vercel API router]', error);
    if (!res.writableEnded) {
      res.statusCode = 500;
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.end(JSON.stringify({ error: 'Internal server error' }));
    }
  }
}
`;
}

// Vercel discovers functions from api/ before the build command runs, so the
// route modules moved out of api/ are no longer reachable through the specific
// rewrites in vercel.json (e.g. /ask -> /api/ask). Point every /api/<route>
// rewrite destination at the single generated index.ts instead, carrying the
// route through __wm_route so requestUrl() can dispatch it. api/mcp.ts stays a
// real function, so /api/mcp keeps its direct destination.
function rewriteVercelDestinations() {
  const vercelPath = join(root, 'vercel.json');
  const raw = readFileSync(vercelPath, 'utf8');
  const rewritten = raw.replace(
    /("destination":\s*"\/api\/)([^"?]+)(\?[^"]*)?(")/g,
    (match, prefix, route, query, suffix) => {
      if (route === 'index') return match;
      if (route === 'mcp' && !query) return match;
      const queryPart = query ? `&${query.slice(1)}` : '';
      return `${prefix}index?__wm_route=${route}${queryPart}${suffix}`;
    },
  );
  if (rewritten !== raw) writeFileSync(vercelPath, rewritten);
}

// Once the consolidation is committed, Vercel must not run prepare:vercel at
// build time — the already-generated api/index.ts makes it throw. The build
// command reduces to upstream's build:full; inventory:facts runs in postinstall.
function rewriteBuildCommand() {
  const vercelPath = join(root, 'vercel.json');
  const raw = readFileSync(vercelPath, 'utf8');
  const rewritten = raw.replace(
    /"buildCommand":\s*"[^"]*"/,
    '"buildCommand": "npm run build:full"',
  );
  if (rewritten !== raw) writeFileSync(vercelPath, rewritten);
}

// The single-function branch keeps only api/index.ts (plus api/mcp.ts) as real
// Vercel Serverless Functions. Vercel maps a request to /api/<path> against an
// api/<path> file, and the consolidated branch no longer has those files (they
// moved into .vercel-api-routes/ so the free plan stays under the function
// limit). Without a catch-all rewrite, every direct frontend call to /api/
// — /api/wm-session, /api/bootstrap, /api/*/v1/*, /api/health — returns 404 and
// the dashboard renders empty. Add { source: '/api/(.*)', destination:
// '/api/index' } so the generated router receives the whole /api namespace and
// restores the original path from the x-matched-path header Vercel attaches to
// rewrite destinations. The destination intentionally carries NO query so
// Vercel keeps forwarding the caller's original query string, which the router
// re-applies alongside the restored path. api/mcp.ts stays a real function and
// takes route precedence, so /api/mcp is unaffected.
function ensureApiCatchAllRewrite() {
  const vercelPath = join(root, 'vercel.json');
  const raw = readFileSync(vercelPath, 'utf8');
  // Idempotent: bail if a rewrite already captures the whole /api namespace.
  if (/"source"\s*:\s*"\/api\/\(\.\*\)"/.test(raw)) return;
  const marker = '"rewrites": [';
  if (!raw.includes(marker)) {
    throw new Error(
      '[prepare-vercel] vercel.json has no "rewrites" array; cannot add the /api catch-all rewrite',
    );
  }
  const insertion = '\n    { "source": "/api/(.*)", "destination": "/api/index" },';
  writeFileSync(vercelPath, raw.replace(marker, marker + insertion));
  console.log('[prepare-vercel] ensured /api/(.*) -> /api/index catch-all rewrite');
}

// docs-stats (used by inventory:facts in postinstall) reads api/bootstrap.js,
// api/health.js, and api/mcp/* files, all of which move into .vercel-api-routes/.
// Add a fallback in its read() helper so the moved reads resolve against the
// staged tree.
function patchDocsStatsReadFallback() {
  const docsStatsPath = join(root, 'scripts', 'docs-stats.mjs');
  const raw = readFileSync(docsStatsPath, 'utf8');
  const marker = "const read = (p) => readFileSync(join(rootOf(), p), 'utf8');";
  if (!raw.includes(marker)) return; // already patched, or upstream changed the helper
  const fallback = `const read = (p) => {
  const primary = join(rootOf(), p);
  try {
    return readFileSync(primary, 'utf8');
  } catch (error) {
    // Vercel single-function deploy branch: api/ route modules are staged into
    // .vercel-api-routes/ (same depth). Resolve api/* reads that moved there so
    // inventory:facts still works during postinstall.
    if (error?.code === 'ENOENT' && p.startsWith('api/')) {
      return readFileSync(join(rootOf(), '.vercel-api-routes', p.slice('api/'.length)), 'utf8');
    }
    throw error;
  }
};`;
  writeFileSync(docsStatsPath, raw.replace(marker, fallback));
}

// The repo's .gitignore ignores internal/ and skills/ directories anywhere in
// the tree (api/internal and api/skills are re-included explicitly). The staged
// route tree mirrors those directories at .vercel-api-routes/internal and
// .vercel-api-routes/skills, which would otherwise be ignored and left out of
// the deploy branch commit. Re-include them the same way upstream re-includes
// their api/ counterparts so the generated api/index.ts routes keep resolving.
// api/mcp.ts imports its implementation from ./mcp/handler, ./mcp/auth, etc.
// After the mcp/ tree moves into .vercel-api-routes/mcp/, rewrite those imports
// to point at the staged tree so the /mcp endpoint keeps working at runtime.
function rewriteMcpEntryImports() {
  const mcpTsPath = join(apiDir, 'mcp.ts');
  const raw = readFileSync(mcpTsPath, 'utf8');
  const rewritten = raw.replace(
    /(from\s+)(['"])\.\/mcp\//g,
    '$1$2../.vercel-api-routes/mcp/',
  );
  if (rewritten !== raw) writeFileSync(mcpTsPath, rewritten);
}

// generate-public-product-facts.mjs statically imports from api/mcp/registry/index.ts.
// After mcp/ moves into .vercel-api-routes/, change the import to use a dynamic
// import with fallback (the .vercel-api-routes/ path on the deploy branch, the
// api/ path on main for `npm run product:facts` during development).
function patchProductFactsImport() {
  const factsPath = join(root, 'scripts', 'generate-public-product-facts.mjs');
  const raw = readFileSync(factsPath, 'utf8');
  const marker = "import { TOOL_REGISTRY, toolAccess } from '../api/mcp/registry/index.ts';";
  if (!raw.includes(marker)) return; // already patched or upstream changed
  const replacement = [
    '// import { TOOL_REGISTRY, toolAccess } from \'../api/mcp/registry/index.ts\';',
    "const mcpRegistryRoot = join(dirname(fileURLToPath(import.meta.url)), '..');",
    "const mcpRegistryAbsPath = join(mcpRegistryRoot, '.vercel-api-routes/mcp/registry/index.ts');",
    "const mcpRegistryPath = existsSync(mcpRegistryAbsPath)",
    "  ? '../.vercel-api-routes/mcp/registry/index.ts'",
    "  : '../api/mcp/registry/index.ts';",
    'const { TOOL_REGISTRY, toolAccess } = await import(mcpRegistryPath);',
  ].join('\n');
  writeFileSync(factsPath, raw.replace(marker, replacement));
}

// build:sitemap's static manifest requires api/mcp/ to exist as a material
// source directory. Keep an empty directory with a .gitkeep so the check
// passes without Vercel counting nested files as functions.
function createEmptyMcpDir() {
  const mcpDir = join(apiDir, 'mcp');
  mkdir(mcpDir, { recursive: true }).catch(() => {});
  writeFileSync(join(mcpDir, '.gitkeep'), '');
}

function allowStagedGitignoreExceptions() {
  const gitignorePath = join(root, '.gitignore');
  const raw = readFileSync(gitignorePath, 'utf8');
  if (raw.includes('!.vercel-api-routes/internal/')) return; // already added
  const block = [
    '',
    '# Vercel single-function deploy branch: the staged route tree mirrors api/,',
    '# so internal/ and skills/ endpoints stay tracked under .vercel-api-routes/.',
    '!.vercel-api-routes/internal/',
    '!.vercel-api-routes/internal/*',
    '!.vercel-api-routes/skills/',
    '!.vercel-api-routes/skills/*',
    '',
  ].join('\n');
  writeFileSync(gitignorePath, raw.replace(/\s*$/, '\n') + block);
}

const FORK_PRO_UNLOCK_PATCHES = [
  {
    description: 'isProUser master unlock (src/services/widget-store.ts)',
    file: join(root, 'src', 'services', 'widget-store.ts'),
    marker:
      'export function isProUser(): boolean {\n' +
      '  return (\n' +
      '    isWidgetFeatureEnabled() ||\n' +
      '    isProWidgetEnabled() ||\n' +
      '    getAuthState().user?.role === \'pro\' ||\n' +
      '    isEntitled()\n' +
      '  );\n' +
      '}',
    replacement:
      'export function isProUser(): boolean {\n' +
      '  // [fork-deploy] Pro gates removed on the Vercel single-function branch.\n' +
      '  void (isEntitled);\n' +
      '  return true;\n' +
      '}',
  },
  {
    description: 'hasPremiumAccess unlock (src/services/panel-gating.ts)',
    file: join(root, 'src', 'services', 'panel-gating.ts'),
    marker:
      "  if (getSecretState('WORLDMONITOR_API_KEY').present) return true;\n" +
      '  if (isProUser()) return true;\n' +
      "  if (authState?.user?.role === 'pro') return true;\n" +
      '  return false;\n' +
      '}',
    replacement:
      "  if (getSecretState('WORLDMONITOR_API_KEY').present) return true;\n" +
      '  if (isProUser()) return true;\n' +
      "  if (authState?.user?.role === 'pro') return true;\n" +
      '  // [fork-deploy] Pro gates removed on the Vercel single-function branch.\n' +
      '  return true;\n' +
      '}',
  },
  {
    description: 'dashboard tab cap removed (src/services/gates/export-resolver.ts)',
    file: join(root, 'src', 'services', 'gates', 'export-resolver.ts'),
    marker:
      "  if (!input.signedIn) return decideTabCap(input, currentTabCount, FREE_TAB_CAP, 'anonymous');\n" +
      '\n' +
      '  const features = input.features;\n' +
      '  if (features === null) return UNCAPPED;\n' +
      '\n' +
      '  const cap = features.maxDashboards;\n' +
      '  // `-1` is the catalog\'s unlimited sentinel (Enterprise). A non-numeric value\n' +
      '  // can only come from a malformed row — the type says required — and an\n' +
      '  // unknown allowance must never cap anyone.\n' +
      '  if (!Number.isFinite(cap) || cap < 0) return UNCAPPED;\n' +
      '\n' +
      '  return decideTabCap(\n' +
      '    input,\n' +
      '    currentTabCount,\n' +
      '    cap,\n' +
      "    getBillingGateOverride(input.billingState) ?? 'free_tier',\n" +
      '  );\n' +
      '}',
    replacement:
      '  // [fork-deploy] Dashboard tab cap removed on the Vercel single-function\n' +
      '  // branch: every session may create unlimited dashboard tabs.\n' +
      '  return UNCAPPED;\n' +
      '  const features = input.features!;\n' +
      '  if (features === null) return UNCAPPED;\n' +
      '\n' +
      '  const cap = features.maxDashboards;\n' +
      '  // `-1` is the catalog\'s unlimited sentinel (Enterprise). A non-numeric value\n' +
      '  // can only come from a malformed row — the type says required — and an\n' +
      '  // unknown allowance must never cap anyone.\n' +
      '  if (!Number.isFinite(cap) || cap < 0) return UNCAPPED;\n' +
      '\n' +
      '  return decideTabCap(\n' +
      '    input,\n' +
      '    currentTabCount,\n' +
      '    cap,\n' +
      "    getBillingGateOverride(input.billingState) ?? 'free_tier',\n" +
      '  );\n' +
      '}',
  },
  {
    description: 'no pro-banner pre-paint reservation (index.html)',
    file: join(root, 'index.html'),
    marker:
      "if(window.self===window.top&&!dismissed&&!entitledHint)document.documentElement.classList.add('wm-pro-banner-reserved');",
    replacement:
      "if(false&&window.self===window.top&&!dismissed&&!entitledHint)document.documentElement.classList.add('wm-pro-banner-reserved');",
  },
];

function forkUnlockProGates() {
  for (const { description, file, marker, replacement } of FORK_PRO_UNLOCK_PATCHES) {
    const raw = readFileSync(file, 'utf8');
    if (!raw.includes(marker)) {
      throw new Error(
        `[fork-unlock] patch marker not found for: ${description}. ` +
        'Upstream likely changed this code — update scripts/prepare-vercel.mjs so the ' +
        'Vercel deploy branch keeps its pro-unlock behaviour.',
      );
    }
    writeFileSync(file, raw.replace(marker, replacement));
  }
  console.log('[prepare-vercel] applied fork pro-unlock patches (panels, dashboards, banner)');
}

const FORK_VARIANT_PATCHES = [
  {
    description: 'variant switcher treats every non-upstream host as local (src/app/panel-layout.ts)',
    file: join(root, 'src', 'app', 'panel-layout.ts'),
    marker:
      "const local = this.ctx.isDesktopApp || location.hostname === 'localhost' || location.hostname === '127.0.0.1';",
    // Keep href '#' so a non-local click stages & reloads instead of hopping to
    // a per-variant subdomain that only the upstream deployment serves.
    replacement:
      "const _h = location.hostname;\n" +
      "const local = this.ctx.isDesktopApp || _h === 'localhost' || _h === '127.0.0.1' || (" +
      "_h !== 'worldmonitor.app' && _h !== 'www.worldmonitor.app' && !_h.endsWith('.worldmonitor.app'));",
    replaceAll: false,
  },
  {
    description: 'variant click handler treats every non-upstream host as local dev (src/app/event-handlers.ts)',
    file: join(root, 'src', 'app', 'event-handlers.ts'),
    marker: "const isLocalDev = location.hostname === 'localhost' || location.hostname === '127.0.0.1';",
    replacement:
      "const isLocalDev = location.hostname === 'localhost' || location.hostname === '127.0.0.1' || " +
      "(location.hostname !== 'worldmonitor.app' && location.hostname !== 'www.worldmonitor.app' " +
      "&& !location.hostname.endsWith('.worldmonitor.app'));",
    // Surface twice: the inline listener binder and the MobilePrimaryNav helper.
    replaceAll: true,
  },
  {
    description: 'SITE_VARIANT resolves locally on non-upstream hosts (src/config/variant.ts)',
    file: join(root, 'src', 'config', 'variant.ts'),
    marker:
      "  if (h === 'localhost' || h === '127.0.0.1') {\n" +
      '    const stored = loadStoredVariant();\n' +
      '    if (isSiteVariant(stored)) return stored;\n' +
      '    return buildVariant;\n' +
      '  }\n' +
      '\n' +
      "  return 'full';\n" +
      '})();',
    replacement:
      '  // [fork-patch] Any host other than the upstream worldmonitor.app deployment\n' +
      '  // (self-hosted, Vercel preview, custom domain) uses local variant selection:\n' +
      '  // an explicit ?variant= URL param wins, then localStorage, then the build\n' +
      '  // default — exactly like localhost / the desktop app.\n' +
      '  const onUpstreamHost =\n' +
      "    h === 'worldmonitor.app' ||\n" +
      "    h === 'www.worldmonitor.app' ||\n" +
      "    h.endsWith('.worldmonitor.app');\n" +
      "  if (h === 'localhost' || h === '127.0.0.1' || !onUpstreamHost) {\n" +
      '    try {\n' +
      "      const urlVariant = new URLSearchParams(window.location.search).get('variant');\n" +
      '      if (isSiteVariant(urlVariant)) return urlVariant;\n' +
      '    } catch { /* ignore */ }\n' +
      '    const stored = loadStoredVariant();\n' +
      '    if (isSiteVariant(stored)) return stored;\n' +
      '    return buildVariant;\n' +
      '  }\n' +
      '\n' +
      "  return 'full';\n" +
      '})();',
    replaceAll: false,
  },
  {
    description: 'prepaint reads the variant from localStorage on non-upstream hosts (index.html)',
    file: join(root, 'index.html'),
    marker:
      "if(!v&&(h==='localhost'||h==='127.0.0.1'||'__TAURI_INTERNALS__' in window))v=localStorage.getItem('worldmonitor-variant');",
    replacement:
      "if(!v&&(h==='localhost'||h==='127.0.0.1'||'__TAURI_INTERNALS__' in window||(" +
      "h!=='worldmonitor.app'&&h!=='www.worldmonitor.app'&&!h.endsWith('.worldmonitor.app'))))v=localStorage.getItem('worldmonitor-variant');",
    replaceAll: false,
  },
];

function forkVariantSwitchPatches() {
  for (const { description, file, marker, replacement, replaceAll } of FORK_VARIANT_PATCHES) {
    const raw = readFileSync(file, 'utf8');
    if (!raw.includes(marker)) {
      throw new Error(
        `[fork-variant] patch marker not found for: ${description}. ` +
        'Upstream likely changed this code — update scripts/prepare-vercel.mjs so the ' +
        'Vercel deploy branch keeps the variant switcher local on the fork.',
      );
    }
    writeFileSync(
      file,
      replaceAll ? raw.split(marker).join(replacement) : raw.replace(marker, replacement),
    );
  }
  console.log('[prepare-vercel] applied fork variant-switch patches (tabs stay local on fork)');
}

// The single-function branch stages the ENTIRE api/ tree into .vercel-api-routes/
// (so Vercel sees one function). source-attribution's SOURCE_ROOTS scan only walks
// api/, so after staging the scan no longer matches the committed
// shared/source-attribution-manifest.json (which references api/... paths) and
// `inventory:facts` / `build:crawlable-corpus` fail the deploy. Make the deploy
// branch scan .vercel-api-routes as the api/ mirror so scan-parity holds again.
const FORK_SOURCE_ATTRIBUTION_PATCHES = [
  {
    description: 'scan .vercel-api-routes as the api/ mirror (walker tail)',
    file: join(root, 'scripts', 'source-attribution.mjs'),
    marker:
      "  for (const root of SOURCE_ROOTS) visit(root);\n" +
      '  return files.sort();\n' +
      '}',
    replacement:
      "  for (const root of SOURCE_ROOTS) visit(root);\n" +
      '  // [fork-patch] single-function branch mirrors api/ into .vercel-api-routes/;\n' +
      '  // scan it too so scan-parity with the committed api/ manifest holds.\n' +
      "  visit('.vercel-api-routes');\n" +
      '  return files.sort();\n' +
      '}',
  },
  {
    description: 'canonical ref path for files staged under .vercel-api-routes/',
    file: join(root, 'scripts', 'source-attribution.mjs'),
    marker:
      '  for (const relativePath of walkSourceFiles(rootDir)) {\n' +
      '    const source = read(rootDir, relativePath);',
    replacement:
      '  for (const relativePath of walkSourceFiles(rootDir)) {\n' +
      "    const refPath = relativePath.startsWith('.vercel-api-routes/') ? 'api/' + relativePath.slice('.vercel-api-routes/'.length) : relativePath;\n" +
      '    const source = read(rootDir, relativePath);',
  },
  {
    description: 'classify staged routes by their canonical api/ path (kind)',
    file: join(root, 'scripts', 'source-attribution.mjs'),
    marker: '      const kind = relativePath === STATUS_FILE',
    replacement: '      const kind = refPath === STATUS_FILE',
  },
  {
    description: 'feed detection uses canonical api/ path',
    file: join(root, 'scripts', 'source-attribution.mjs'),
    marker: ': FEED_FILES.has(relativePath)',
    replacement: ': FEED_FILES.has(refPath)',
  },
  {
    description: 'record reference against canonical api/ path',
    file: join(root, 'scripts', 'source-attribution.mjs'),
    marker: 'recordHost(host, kind, relativePath);',
    replacement: 'recordHost(host, kind, refPath);',
  },
];

function forkSourceAttributionScan() {
  for (const { description, file, marker, replacement } of FORK_SOURCE_ATTRIBUTION_PATCHES) {
    const raw = readFileSync(file, 'utf8');
    if (!raw.includes(marker)) {
      throw new Error(
        `[fork-attribution] patch marker not found for: ${description}. ` +
        'Upstream likely changed source-attribution.mjs — update scripts/prepare-vercel.mjs ' +
        'so the Vercel deploy branch keeps scan-parity after staging into .vercel-api-routes/.',
      );
    }
    writeFileSync(file, raw.replace(marker, replacement));
  }
  console.log('[prepare-vercel] applied fork source-attribution scan remap (.vercel-api-routes -> api/)');
}

async function main() {
  if (!(await stat(apiDir).catch(() => null))) {
    throw new Error('api/ directory is missing; the canonical repository layout is required');
  }
  // --force regenerates an existing deployment branch in place: drop the
  // previous generated entry point and staging tree first so the transform is
  // idempotent (upstream itself ships an api/index.ts dynamic router that the
  // generated static import map must replace).
  if (await stat(generatedIndex).catch(() => null)) {
    if (!force) {
      throw new Error('api/index.ts already exists; remove the generated deployment artifact before preparing again (or use --force)');
    }
    await rm(generatedIndex, { force: true });
  }

  const files = await collectFiles(apiDir);
  const routes = sortRoutes(
    files
      .map((relativePath) => ({ relativePath, routePath: routePathFromFile(relativePath) }))
      .filter((entry) => entry.routePath),
  );

  if (check || !shouldPrepare()) {
    console.log(
      `[prepare-vercel] ${routes.length} route modules discovered; ` +
      (shouldPrepare() ? 'deployment transformation enabled' : 'repository unchanged (use VERCEL=1 or --force to stage)'),
    );
    return;
  }

  if (await stat(stagingDir).catch(() => null)) {
    if (!force) {
      throw new Error(`${relative(root, stagingDir)} already exists; refusing to overwrite a previous staging tree (or use --force)`);
    }
    await rm(stagingDir, { recursive: true, force: true });
  }

  // Stage the ENTIRE api/ tree (except test files) into .vercel-api-routes/ at
  // the same depth as api/, so relative imports keep resolving. Non-underscore
  // route files are removed from api/ so Vercel discovers only the generated
  // router and stays within the Hobby function limit.
  await mkdir(stagingDir, { recursive: true });

  for (const relativePath of files) {
    if (/\.(test|spec)\./.test(relativePath)) continue;
    const src = join(apiDir, relativePath);
    const dest = join(stagingDir, relativePath);
    const destDir = dirname(dest);
    await mkdir(destDir, { recursive: true });
    await cp(src, dest);
    if (!staysInApi(relativePath)) {
      await rm(src, { force: true });
    }
  }

  patchDocsStatsReadFallback();
  rewriteMcpEntryImports();
  patchProductFactsImport();
  allowStagedGitignoreExceptions();
  createEmptyMcpDir();
  forkUnlockProGates();
  forkVariantSwitchPatches();
  forkSourceAttributionScan();


  await writeFile(generatedIndex, renderIndex(routes));
  rewriteVercelDestinations();
  ensureApiCatchAllRewrite();
  rewriteBuildCommand();

  const stagedCount = files.filter((relativePath) => !staysInApi(relativePath) && !/\.(test|spec)\./.test(relativePath)).length;
  console.log(
    `[prepare-vercel] staged ${stagedCount} api files (${routes.length} routes) behind api/index.ts`,
  );
}

await main();
