// @ts-nocheck
/* AUTO-GENERATED by scripts/prepare-vercel.mjs. Do not edit. */
// Vercel sees this file as the only API function. The source route modules are
// staged in .vercel-api-routes/ (same depth as api/, so relative imports of
// ../server/... keep resolving) and loaded through this generated static
// import map.

const routeLoaders = {
  "/supply-chain/v1/multi-sector-cost-shock": () => import('../.vercel-api-routes/supply-chain/v1/multi-sector-cost-shock'),
  "/http-message-signatures-directory": () => import('../.vercel-api-routes/http-message-signatures-directory'),
  "/supply-chain/v1/country-products": () => import('../.vercel-api-routes/supply-chain/v1/country-products'),
  "/invalidate-user-api-key-cache": () => import('../.vercel-api-routes/invalidate-user-api-key-cache'),
  "/supply-chain/hormuz-tracker": () => import('../.vercel-api-routes/supply-chain/hormuz-tracker'),
  "/internal/brief-why-matters": () => import('../.vercel-api-routes/internal/brief-why-matters'),
  "/internal/mcp-grant-context": () => import('../.vercel-api-routes/internal/mcp-grant-context'),
  "/oauth-authorization-server": () => import('../.vercel-api-routes/oauth-authorization-server'),
  "/correlation-runtime-mode": () => import('../.vercel-api-routes/correlation-runtime-mode'),
  "/oauth-protected-resource": () => import('../.vercel-api-routes/oauth-protected-resource'),
  "/skills/fetch-agentskills": () => import('../.vercel-api-routes/skills/fetch-agentskills'),
  "/internal/mcp-grant-mint": () => import('../.vercel-api-routes/internal/mcp-grant-mint'),
  "/discord/oauth/callback": () => import('../.vercel-api-routes/discord/oauth/callback'),
  "/notification-channels": () => import('../.vercel-api-routes/notification-channels'),
  "/scenario/v1/templates": () => import('../.vercel-api-routes/scenario/v1/templates'),
  "/slack/oauth/callback": () => import('../.vercel-api-routes/slack/oauth/callback'),
  "/discord/oauth/start": () => import('../.vercel-api-routes/discord/oauth/start'),
  "/oauth/authorize-pro": () => import('../.vercel-api-routes/oauth/authorize-pro'),
  "/seed-contract-probe": () => import('../.vercel-api-routes/seed-contract-probe'),
  "/scenario/v1/status": () => import('../.vercel-api-routes/scenario/v1/status'),
  "/embed/entitlement": () => import('../.vercel-api-routes/embed/entitlement'),
  "/slack/oauth/start": () => import('../.vercel-api-routes/slack/oauth/start'),
  "/analytics-health": () => import('../.vercel-api-routes/analytics-health'),
  "/brief/share-url": () => import('../.vercel-api-routes/brief/share-url'),
  "/create-checkout": () => import('../.vercel-api-routes/create-checkout'),
  "/customer-portal": () => import('../.vercel-api-routes/customer-portal'),
  "/oauth/authorize": () => import('../.vercel-api-routes/oauth/authorize'),
  "/product-catalog": () => import('../.vercel-api-routes/product-catalog'),
  "/reverse-geocode": () => import('../.vercel-api-routes/reverse-geocode'),
  "/scenario/v1/run": () => import('../.vercel-api-routes/scenario/v1/run'),
  "/security/report": () => import('../.vercel-api-routes/security/report'),
  "/user/mcp-revoke": () => import('../.vercel-api-routes/user/mcp-revoke'),
  "/me/entitlement": () => import('../.vercel-api-routes/me/entitlement'),
  "/oauth/register": () => import('../.vercel-api-routes/oauth/register'),
  "/user/mcp-quota": () => import('../.vercel-api-routes/user/mcp-quota'),
  "/symbol-search": () => import('../.vercel-api-routes/symbol-search'),
  "/telegram-feed": () => import('../.vercel-api-routes/telegram-feed'),
  "/youtube/embed": () => import('../.vercel-api-routes/youtube/embed'),
  "/chat-analyst": () => import('../.vercel-api-routes/chat-analyst'),
  "/latest-brief": () => import('../.vercel-api-routes/latest-brief'),
  "/widget-agent": () => import('../.vercel-api-routes/widget-agent'),
  "/youtube/live": () => import('../.vercel-api-routes/youtube/live'),
  "/cache-purge": () => import('../.vercel-api-routes/cache-purge'),
  "/oauth/token": () => import('../.vercel-api-routes/oauth/token'),
  "/oref-alerts": () => import('../.vercel-api-routes/oref-alerts'),
  "/referral/me": () => import('../.vercel-api-routes/referral/me'),
  "/seed-health": () => import('../.vercel-api-routes/seed-health'),
  "/agent-auth": () => import('../.vercel-api-routes/agent-auth'),
  "/polymarket": () => import('../.vercel-api-routes/polymarket'),
  "/user-prefs": () => import('../.vercel-api-routes/user-prefs'),
  "/wm-session": () => import('../.vercel-api-routes/wm-session'),
  "/bootstrap": () => import('../.vercel-api-routes/bootstrap'),
  "/mcp-proxy": () => import('../.vercel-api-routes/mcp-proxy'),
  "/rss-proxy": () => import('../.vercel-api-routes/rss-proxy'),
  "/docs-mcp": () => import('../.vercel-api-routes/docs-mcp'),
  "/download": () => import('../.vercel-api-routes/download'),
  "/fwdstart": () => import('../.vercel-api-routes/fwdstart'),
  "/og-story": () => import('../.vercel-api-routes/og-story'),
  "/md-twin": () => import('../.vercel-api-routes/md-twin'),
  "/opensky": () => import('../.vercel-api-routes/opensky'),
  "/version": () => import('../.vercel-api-routes/version'),
  "/gpsjam": () => import('../.vercel-api-routes/gpsjam'),
  "/health": () => import('../.vercel-api-routes/health'),
  "/notify": () => import('../.vercel-api-routes/notify'),
  "/story": () => import('../.vercel-api-routes/story'),
  "/a2a": () => import('../.vercel-api-routes/a2a'),
  "/ask": () => import('../.vercel-api-routes/ask'),
  "/geo": () => import('../.vercel-api-routes/geo'),
  "/mcp": () => import('../.vercel-api-routes/mcp'),
  "/v2/shipping/webhooks/:subscriberId/:action": () => import('../.vercel-api-routes/v2/shipping/webhooks/[subscriberId]/[action]'),
  "/brief/carousel/:userId/:issueDate/:page": () => import('../.vercel-api-routes/brief/carousel/[userId]/[issueDate]/[page]'),
  "/v2/shipping/webhooks/:subscriberId": () => import('../.vercel-api-routes/v2/shipping/webhooks/[subscriberId]'),
  "/brief/:userId/:issueDate": () => import('../.vercel-api-routes/brief/[userId]/[issueDate]'),
  "/consumer-prices/v1/:rpc": () => import('../.vercel-api-routes/consumer-prices/v1/[rpc]'),
  "/positive-events/v1/:rpc": () => import('../.vercel-api-routes/positive-events/v1/[rpc]'),
  "/infrastructure/v1/:rpc": () => import('../.vercel-api-routes/infrastructure/v1/[rpc]'),
  "/displacement/v1/:rpc": () => import('../.vercel-api-routes/displacement/v1/[rpc]'),
  "/intelligence/v1/:rpc": () => import('../.vercel-api-routes/intelligence/v1/[rpc]'),
  "/supply-chain/v1/:rpc": () => import('../.vercel-api-routes/supply-chain/v1/[rpc]'),
  "/brief/public/:hash": () => import('../.vercel-api-routes/brief/public/[hash]'),
  "/prediction/v1/:rpc": () => import('../.vercel-api-routes/prediction/v1/[rpc]'),
  "/resilience/v1/:rpc": () => import('../.vercel-api-routes/resilience/v1/[rpc]'),
  "/seismology/v1/:rpc": () => import('../.vercel-api-routes/seismology/v1/[rpc]'),
  "/radiation/v1/:rpc": () => import('../.vercel-api-routes/radiation/v1/[rpc]'),
  "/sanctions/v1/:rpc": () => import('../.vercel-api-routes/sanctions/v1/[rpc]'),
  "/aviation/v1/:rpc": () => import('../.vercel-api-routes/aviation/v1/[rpc]'),
  "/conflict/v1/:rpc": () => import('../.vercel-api-routes/conflict/v1/[rpc]'),
  "/economic/v1/:rpc": () => import('../.vercel-api-routes/economic/v1/[rpc]'),
  "/forecast/v1/:rpc": () => import('../.vercel-api-routes/forecast/v1/[rpc]'),
  "/maritime/v1/:rpc": () => import('../.vercel-api-routes/maritime/v1/[rpc]'),
  "/military/v1/:rpc": () => import('../.vercel-api-routes/military/v1/[rpc]'),
  "/research/v1/:rpc": () => import('../.vercel-api-routes/research/v1/[rpc]'),
  "/scenario/v1/:rpc": () => import('../.vercel-api-routes/scenario/v1/[rpc]'),
  "/v2/shipping/:rpc": () => import('../.vercel-api-routes/v2/shipping/[rpc]'),
  "/wildfire/v1/:rpc": () => import('../.vercel-api-routes/wildfire/v1/[rpc]'),
  "/climate/v1/:rpc": () => import('../.vercel-api-routes/climate/v1/[rpc]'),
  "/imagery/v1/:rpc": () => import('../.vercel-api-routes/imagery/v1/[rpc]'),
  "/natural/v1/:rpc": () => import('../.vercel-api-routes/natural/v1/[rpc]'),
  "/thermal/v1/:rpc": () => import('../.vercel-api-routes/thermal/v1/[rpc]'),
  "/giving/v1/:rpc": () => import('../.vercel-api-routes/giving/v1/[rpc]'),
  "/health/v1/:rpc": () => import('../.vercel-api-routes/health/v1/[rpc]'),
  "/market/v1/:rpc": () => import('../.vercel-api-routes/market/v1/[rpc]'),
  "/unrest/v1/:rpc": () => import('../.vercel-api-routes/unrest/v1/[rpc]'),
  "/webcam/v1/:rpc": () => import('../.vercel-api-routes/webcam/v1/[rpc]'),
  "/batch/v1/:rpc": () => import('../.vercel-api-routes/batch/v1/[rpc]'),
  "/cyber/v1/:rpc": () => import('../.vercel-api-routes/cyber/v1/[rpc]'),
  "/leads/v1/:rpc": () => import('../.vercel-api-routes/leads/v1/[rpc]'),
  "/trade/v1/:rpc": () => import('../.vercel-api-routes/trade/v1/[rpc]'),
  "/news/v1/:rpc": () => import('../.vercel-api-routes/news/v1/[rpc]'),
  "/*": () => import('../.vercel-api-routes/[...notfound]'),
};
const nodeStyleRoutes = new Set(["/story","/og-story"]);
const routePatterns = Object.entries(routeLoaders).map(([pattern, load]) => ({ pattern, load }));

function requestUrl(req) {
  const host = req.headers?.host || 'localhost';
  const protocol = req.headers?.['x-forwarded-proto'] || 'https';
  const rawUrl = req.url || '/';
  const url = new URL(rawUrl, protocol + '://' + host);
  const stagedRoute = url.searchParams.get('__wm_route');

  // The rewrite carries the original route explicitly. The header fallbacks
  // cover Vercel preview invocations and direct calls to /api/index.
  if (stagedRoute !== null) {
    url.searchParams.delete('__wm_route');
    url.pathname = '/api/' + stagedRoute.replace(/^\/+/, '');
  } else if (url.pathname === '/api/index' || url.pathname === '/api/index.ts') {
    const originalPath = req.headers?.['x-matched-path'] || req.headers?.['x-original-url'];
    if (typeof originalPath === 'string' && originalPath.startsWith('/api/')) {
      const original = new URL(originalPath, url);
      url.pathname = original.pathname;
      url.search = original.search;
    }
  }
  return url;
}

function routeMatches(pattern, pathname) {
  const patternParts = pattern.split('/').filter(Boolean);
  const pathParts = pathname.split('/').filter(Boolean);
  if (patternParts.at(-1) === '*') {
    if (pathParts.length < patternParts.length - 1) return false;
  } else if (patternParts.length !== pathParts.length) {
    return false;
  }
  return patternParts.every((part, index) => part === '*' || part.startsWith(':') || part === pathParts[index]);
}

function findRoute(pathname) {
  const apiPath = pathname.replace(/^\/api(?=\/$|\/)/, '') || '/';
  return routePatterns.find(({ pattern }) => routeMatches(pattern, apiPath));
}

function webRequest(req, url) {
  const headers = new Headers();
  for (const [name, value] of Object.entries(req.headers || {})) {
    if (Array.isArray(value)) headers.set(name, value.join(', '));
    else if (value != null) headers.set(name, String(value));
  }
  const init = { method: req.method || 'GET', headers };
  if (init.method !== 'GET' && init.method !== 'HEAD') {
    init.body = req;
    init.duplex = 'half';
  }
  return new Request(url, init);
}

async function sendWebResponse(res, response) {
  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  if (!response.body) {
    res.end();
    return;
  }
  const reader = response.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      res.write(value);
    }
  } finally {
    res.end();
  }
}

export default async function handler(req, res) {
  const url = requestUrl(req);
  const route = findRoute(url.pathname);
  if (!route) {
    res.statusCode = 404;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'Route not found' }));
    return;
  }

  try {
    const module = await route.load();
    const routeHandler = module.default;
    if (typeof routeHandler !== 'function') throw new Error('Route has no default handler');

    if (nodeStyleRoutes.has(route.pattern)) {
      await routeHandler(req, res);
      return;
    }

    const response = await routeHandler(
      webRequest(req, url),
      { waitUntil: (promise) => Promise.resolve(promise).catch(() => {}) },
    );
    if (response instanceof Response) {
      await sendWebResponse(res, response);
    } else if (!res.writableEnded) {
      res.statusCode = 500;
      res.end(JSON.stringify({ error: 'Route did not return a Response' }));
    }
  } catch (error) {
    console.error('[Vercel API router]', error);
    if (!res.writableEnded) {
      res.statusCode = 500;
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.end(JSON.stringify({ error: 'Internal server error' }));
    }
  }
}
